//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int cod_producto { get; set; }
        public string producto1 { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string serie { get; set; }
        public string detalle { get; set; }
        public string tipo { get; set; }
        public Nullable<int> cod_proveedor { get; set; }
        public Nullable<int> cod_bodega { get; set; }
        public string precio { get; set; }
        public Nullable<int> cod_medidacompra { get; set; }
        public Nullable<int> cod_medidadespacho { get; set; }
        public Nullable<int> cod_met_costo { get; set; }
        public string imagen { get; set; }
        public Nullable<int> cod_status { get; set; }
        public Nullable<int> cod_stock { get; set; }
    }
}
