//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        public int cod_sucursal { get; set; }
        public string sucursal1 { get; set; }
        public Nullable<int> cod_status { get; set; }
    }
}
