//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferencia
    {
        public int cod_transferencia { get; set; }
        public int cod_stock_sale { get; set; }
        public int cantidad_transferir { get; set; }
        public int cod_medida { get; set; }
        public int cod_stock_entra { get; set; }
        public Nullable<int> cod_usuario { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
