//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.transferencia = new HashSet<transferencia>();
        }
    
        public int cod_usuario { get; set; }
        public string usuario { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public Nullable<int> cod_status { get; set; }
        public Nullable<int> cod_rol { get; set; }
        public Nullable<int> cod_costo { get; set; }
        public Nullable<int> cod_sucursal { get; set; }
        public Nullable<int> cod_bodega { get; set; }
        public string email { get; set; }
        public string salt { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transferencia> transferencia { get; set; }
    }
}
